application: dinesharunblog
version: 4
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: (.*)(/)$
  script: \1/index.php

- url: /(.+\.php)$
  script: \1

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /scripts/(.*)
  static_files: scripts/\1
  upload: scripts/(.*)
  application_readable: true

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)
  application_readable: true

- url: /art
  static_files: art
  upload: art/(.*)
  application_readable: true

- url: /tech
  static_files: tech
  upload: tech/(.*)
  application_readable: true
